name: pull-request

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: '14'
      - name: Install Dependencies
        run: npm install -g yarn
      - name: Lerna bootstrap
        run: yarn run bootstrap
      - name: Build Projects
        run: yarn run build
      - name: Test Projects
        run: yarn run test
      - name: Lint Projects
        run: yarn run lint